version: '3'

services: 

  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: primeira-api-nestjs-imersao-testando
    ports: 
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    build: .docker/postgres
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest_api